spring:
  application:
    name: facility-server # <--- This is the name it registers with in Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/facilityservice
    username: root
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis  # Tell Spring to use Redis for caching
  data:
    redis:
      host: localhost  # Change to "redis" if running in Docker
      port: 6390
