spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryservice
    username: root
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085 # The service runs on this port

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
