spring:
  application:
    name: product-server # <--- This is the name it registers with in Eureka
  datasource:
    url: jdbc:postgresql://localhost:5433/productservice
    username: root
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis  # Tell Spring to use Redis for caching
  data:
    redis:
      host: 127.0.0.1  # Change to "redis" if running in Docker
      port: 6390
  #
##  for finding config server
  cloud:
    config:
      discovery:
        enabled: true  # Enable Eureka-based config server lookup
        service-id: config-server # <-- Eureka service name of your config server
  config:
    import: "optional:configserver:"


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

cnj:
  message: gds
